In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [8]:
df.shape

(5572, 3)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [15]:
x_train.shape

(4457,)

In [16]:
x_test.shape

(1115,)

In [17]:
type(x_train)

pandas.core.series.Series

In [20]:
x_train[:4][239]

"New Theory: Argument wins d SITUATION, but loses the PERSON. So dont argue with ur friends just.. . . . kick them &amp; say, I'm always correct.!"

In [21]:
type(y_train)

pandas.core.series.Series

In [22]:
y_train[:4]

239     0
5298    0
1340    0
3323    0
Name: spam, dtype: int64

In [23]:
type(x_train.values)

numpy.ndarray

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59121 stored elements and shape (4457, 7731)>

In [25]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
x_train_cv.shape

(4457, 7731)

In [28]:
v.get_feature_names_out().shape

(7731,)

In [29]:
v.get_feature_names_out()[6847]

'thought'

In [32]:
v.vocabulary_

{'new': 4754,
 'theory': 6809,
 'argument': 1047,
 'wins': 7520,
 'situation': 6177,
 'but': 1561,
 'loses': 4206,
 'the': 6795,
 'person': 5151,
 'so': 6261,
 'dont': 2410,
 'argue': 1045,
 'with': 7535,
 'ur': 7183,
 'friends': 3014,
 'just': 3880,
 'kick': 3930,
 'them': 6803,
 'amp': 937,
 'say': 5903,
 'always': 923,
 'correct': 2003,
 'll': 4154,
 'hand': 3312,
 'her': 3418,
 'my': 4660,
 'phone': 5178,
 'to': 6919,
 'chat': 1733,
 'wit': 7534,
 'every': 2665,
 'monday': 4559,
 'nxt': 4865,
 'week': 7421,
 'vl': 7296,
 'be': 1260,
 'completing': 1924,
 'ok': 4909,
 'darlin': 2156,
 'supose': 6594,
 'it': 3762,
 'was': 7373,
 'worry': 7589,
 'too': 6954,
 'much': 4628,
 'have': 3362,
 'do': 2373,
 'some': 6273,
 'film': 2849,
 'stuff': 6522,
 'mate': 4376,
 'and': 949,
 'then': 6806,
 'babysit': 1180,
 'again': 852,
 'you': 7689,
 'can': 1616,
 'call': 1592,
 'me': 4402,
 'there': 6812,
 'xx': 7640,
 'sun': 6579,
 'ah': 863,
 'thk': 6837,
 'mayb': 4394,
 'if': 3605,
 'dun': 2487,


In [37]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
np.where(x_train_np[0]!=0)

(array([ 923,  937, 1045, 1047, 1561, 2003, 2410, 3014, 3880, 3930, 4206,
        4754, 5151, 5903, 6177, 6261, 6795, 6803, 6809, 7183, 7520, 7535]),)

In [40]:
x_train[:4][239]

"New Theory: Argument wins d SITUATION, but loses the PERSON. So dont argue with ur friends just.. . . . kick them &amp; say, I'm always correct.!"

In [41]:
x_train_np[0][1045]

np.int64(1)

In [43]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB() 
model.fit(x_train_cv, y_train)

MultinomialNB()

In [44]:
x_test_cv = v.transform(x_test)

In [47]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       967
           1       0.99      0.91      0.95       148

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [48]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])